#!/bin/bash

echo "Mpegscript Music File Converter"
echo "Input file type, either flac or m4a."
read filetype

# Convert lossless files to 320kb mp3 files and change the file extension. 
# Also copy over the ID3 tags.
for file in *."${filetype}"
do
  ffmpeg -i "$file" -ab 320k -map_metadata 0 -id3v2_version 3 "${file%.${filetype}}.mp3";
done

# Remove lossless files.
rm *."${filetype}"
