#!/bin/bash

dev_directory="/home/chris/Development/Websites/chriswoodtech"
dev_session="tmux-dev-server"
session_exists="$(tmux list-sessions | grep ${dev_session})"
window_1="vite-git"
window_2="neovim"

# Test for active session before initializing tmux-dev-server.
if [[ ${session_exists} = "" ]]
then
    tmux new-session -d -s "${dev_session}" -c ${dev_directory} 
    tmux rename-window -t 0 "${window_1}"
    tmux send-keys -t "${window_1}" "npm run dev" enter
    tmux split-window -t "${window_1}" -c ${dev_directory} -h
    tmux send-keys "git status" enter
    tmux new-window -c ${dev_directory} -n ${window_2}
    tmux attach-session -t ${dev_session}
fi
